[package]
name = "greatgramma-compile"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[dependencies]
cfgrammar = "=0.15.0"
derivre = "=0.3.12"
greatgramma-core = { path = "../greatgramma-core" }
regex-syntax = "=0.8.11"
serde_json = "=1.0.151"

[lints]
workspace = true
